name: Release
on:
  push:
    branches: [master, ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk
          architecture: x64
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install atlassian-plugin-sdk
        run: |
          wget -nv https://packages.atlassian.com/api/gpg/key/public
          sudo apt-key add public
          sudo sh -c 'echo "deb https://packages.atlassian.com/atlassian-sdk-deb stable contrib" >> /etc/apt/sources.list'
          sudo apt-get -q -y install apt-transport-https
          sudo apt-get -q update
          sudo apt-get -q -y install atlassian-plugin-sdk
      - name: Build packages
        run: atlas-package 
      - name: Create  Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: flase
          files: target/jtex-0.5.jar
